config/routes.rb
Rails.application.routes.draw do
#   root :to => 'create_tasks#index'
  resources :create_tasks
   get 'greetings/hello'
   get 'greetings/goodbye'
   get 'greetings/test_array'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/create_task.rb
class CreateTask < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/create_tasks_controller.rb
class CreateTasksController < ApplicationController
  before_action :set_create_task, only: %i[ show edit update destroy ]

  # GET /create_tasks or /create_tasks.json
  def index
    @create_tasks = CreateTask.all
  end

  # GET /create_tasks/1 or /create_tasks/1.json
  def show
  end

  # GET /create_tasks/new
  def new
    @create_task = CreateTask.new
  end

  # GET /create_tasks/1/edit
  def edit
  end

  # POST /create_tasks or /create_tasks.json
  def create
    @create_task = CreateTask.new(create_task_params)

    respond_to do |format|
      if @create_task.save
        format.html { redirect_to create_task_url(@create_task), notice: "Create task was successfully created." }
        format.json { render :show, status: :created, location: @create_task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @create_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_tasks/1 or /create_tasks/1.json
  def update
    respond_to do |format|
      if @create_task.update(create_task_params)
        format.html { redirect_to create_task_url(@create_task), notice: "Create task was successfully updated." }
        format.json { render :show, status: :ok, location: @create_task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @create_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_tasks/1 or /create_tasks/1.json
  def destroy
    @create_task.destroy

    respond_to do |format|
      format.html { redirect_to create_tasks_url, notice: "Create task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_task
      @create_task = CreateTask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_task_params
      params.fetch(:create_task, {})
    end

end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
    #クラス変数を初期化
    @@default = "あいさつします"

  def hello
    num = 6
    greeting = "いらっしゃいませ"
    # 条件分岐
    if num == 1 then
      @message = "こんにちは、ご機嫌いかがですか"
    elsif num > 5 then
      # インスタンス変数にローカル変数を代入
      @message = greeting
    else
      # インスタンス変数にクラス変数を代入
      # どうして代入できるんだろう？
      @message = @@default
    end
  end

  def goodbye
    # メソッドを呼び出してインスタンス変数messageに代入
    @message = add_postfix("さようなら")
  end

  def add_postfix(originalMessage)
    # 引数を受け取り文字列を追加
    return originalMessage + "ざます"
  end

  def test_array
    # 連想配列を作成
    @food_array = {"りんご" => "100円", "みかん" => "150円", "バナナ" => "300円"}
    # 食べ物配列からキーをもとに値を取得
    apple_price = @food_array["りんご"]
    # 食べ物配列に要素を追加（値を更新するときも同じ書き方）
    @food_array["シャインマスカット"] = "4000円"
    # 食べ物配列からみかんを削除
    @food_array.delete("みかん")

    # 配列を作成（Javaと違って要素数を増やすことができる）
    @animal_array = ["ライオン", "キリン", "ウサギ"]
    # インデックスを指定して追加（値を更新するときも同じ書き方）
    @animal_array[4] = "しまうま"
    # 末尾に追加　方法その１
    @animal_array("アルパカ")
    # 末尾に追加　方法その２
    @animal_array << "リス"
    #
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_tasks_helper.rb
module CreateTasksHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/create_tasks/_create_task.html.erb
<h1>タスク一覧</h1>
<table>
  <thead>
    <tr>
      <th>タスク名</th>
    </tr>
  </thead>
  <tbody>
    <% @create_tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/create_tasks/_form.html.erb
<%= form_with(model: create_task) do |form| %>
  <% if create_task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(create_task.errors.count, "error") %> prohibited this create_task from being saved:</h2>

      <ul>
        <% create_task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/create_tasks/edit.html.erb
<h1>Editing create task</h1>

<%= render "form", create_task: @create_task %>

<br>

<div>
  <%= link_to "Show this create task", @create_task %> |
  <%= link_to "Back to create tasks", create_tasks_path %>
</div>

app/views/create_tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Create tasks</h1>

<div id="create_tasks">
  <% @create_tasks.each do |create_task| %>
    <%= render create_task %>
    <p>
      <%= link_to "Show this create task", create_task %>
    </p>
  <% end %>
</div>

<%= link_to "New create task", new_create_task_path %>

app/views/create_tasks/new.html.erb
<h1>New create task</h1>

<%= render "form", create_task: @create_task %>

<br>

<div>
  <%= link_to "Back to create tasks", create_tasks_path %>
</div>

app/views/create_tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @create_task %>

<div>
  <%= link_to "Edit this create task", edit_create_task_path(@create_task) %> |
  <%= link_to "Back to create tasks", create_tasks_path %>

  <%= button_to "Destroy this create task", @create_task, method: :delete %>
</div>

app/views/greetings/goodbye.html.erb
<h1>さよならごあいさつ</h1>
<p><%= @message %></p>

app/views/greetings/hello.html.erb
<h1>ごあいさつ</h1>
<p><%= @message %></p>

app/views/greetings/test_array.html.erb
<h1>連想配列</h1>
  <% @food_array.each do |food, price| %>
    <tr>
      <td><%= food %></td>
      <td><%= price %></td>
      <br>
    </tr>
  <% end %>
<br>
<h1>配列</h1>
  <% @animal_array.each do |animal| %>
    <tr>
      <td><%= animal %></td>
      <br>
    </tr>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>